# please refer to the datura documentation for a full list of configurable settings
# any custom settings you create here will be accessible in instances of classes
# like FileTei and TeiToEs ( @options["setting_name"] )
# you may also create new environments

# please put any sensitive information or computer specific settings in private.yml!

default:
  # please fill in the name of your collection here
  # collection:

  data_base: https://cdrhmedia.unl.edu  # (do not include /data/ in path)
  media_base: https://cdrhmedia.unl.edu

  # refer to the documentation for details about overriding the XSL
  # html_html_xsl:
  # tei_html_xsl: scripts/xslt/tei.xsl
  # vra_html_xsl:

  variables_html:
    site_url: override_in_public
    image_large: 800
    image_thumb: 150

development:
  es_index: edit_public_config
  es_path: https://edit_public_config/elastic
  data_base: https://override_public

# production:
  # limit processed files by adding allowed ids on newlines in a file
  # allowed_files: config/allowed.txt

