# please refer to the datura documentation for a full list of configurable settings
# any custom settings you create here will be accessible in instances of classes
# like FileTei and TeiToEs ( @options["setting_name"] )
# you may also create new environments

# please put any sensitive information or computer specific settings in private.yml!

default:
  shortname: whitman-other_books
  collection: whitman-other_books
  site_url: https://whitmanarchive.org
  tei_html_xsl: scripts/overrides/tei_to_html.xsl
  media_base: https://whitmanarchive.org/media
  data_base: https://whitmanarchive.org/media
  variables_html:
    image_large: 1200
    image_thumb: 80

development:
  api_version: '2.0'
  data_base: https://whitman-dev.unl.edu/media
  es_path: https://whitman-dev.unl.edu/elastic
  es_index: api_v2
  site_url: https://whitman-dev.unl.edu

production:
  site_url: https://whitmanarchive.org
# production:
  # limit processed files by adding allowed ids on newlines in a file
  # allowed_files: config/allowed.txt

